# Generated by Django 2.2.4 on 2020-08-05 18:43

from django.db import migrations


def migrate_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():

        owner, result = Owner.objects.get_or_create(full_name=flat.owner,
                                             phonenumber=flat.owners_phonenumber,
                                             phone_pure=flat.owner_phone_pure)

        if result:
            owner.flat.set([flat])
        else:
            owner.flat.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_owner'),
    ]

    operations = [
        migrations.RunPython(migrate_owner)
    ]
