# Generated by Django 2.2.4 on 2020-08-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200805_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Flat',
            name='owner'
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owners_phonenumber'
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owner_phone_pure'
        ),
    ]
